# This is not automatically generated by ros2nix. Since it is not
# officially part of ROS.

{ stdenv, buildRosPackage, fetchFromGitHub }:

let pname = "urdfdom_headers";
    version = "1.0.4";
    rosdistro = "kinetic";

in buildRosPackage {
  name = "${pname}-${version}";

  propagatedBuildInputs  = [];

  src = fetchFromGitHub {
    owner = "ros";
    repo = "${pname}";
    rev = "${version}";
    sha256 = "0vk34r9v75fy0z6xafkwhqf7qg5ncd8rd33454yna6jl94pcdqcx";
  };

  meta = {
    description = "urdfdom_headers";
    homepage = http://wiki.ros.org/urdfdom_headers;
    license = stdenv.lib.licenses.bsd3;
  };
}
