# This is not automatically generated by ros2nix. Since it is not
# officially part of ROS.

{ stdenv, buildRosPackage, fetchFromGitHub,
  tinyxml, urdfdom_headers, console_bridge }:

let pname = "urdfdom";
    version = "1.0.3";
    rosdistro = "kinetic";

    urdfdomComfigCMakeInPatch = ./urdfdom-config.cmake.in.patch;

in buildRosPackage {
  name = "${pname}-${version}";

  propagatedBuildInputs  = [
    tinyxml urdfdom_headers
    console_bridge
  ];

  src = fetchFromGitHub {
    owner = "ros";
    repo = "${pname}";
    rev = "${version}";
    sha256 = "1i6xd6rhz024cwrhi5h7g4j7qv5v0b708mnlghk2vsczfjxshy6m";
  };

  patchPhase = ''
    patch ./cmake/urdfdom-config.cmake.in ${urdfdomComfigCMakeInPatch}
  '';

  meta = {
    description = "urdfdom";
    homepage = http://wiki.ros.org/urdfdom;
    license = stdenv.lib.licenses.bsd3;
  };
}
